#
# Docker NodeJS Typescript Starter
# Example Docker Compose file
#

# For more information about the directives defined here:
# https://docs.docker.com/compose/compose-file/

# Docker compose file version
version: "3.7"

services:
  app:
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    command: npm run test
    depends_on:
      - db

  db:
    image: mongo:3.6
    container_name: mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    env_file:
      - .env
    restart: always
    command: mongod --auth
    volumes:
      #add persistent storage
      - db:/data/db
      #add path to startup script
      - ./entrypoint/:/docker-entrypoint-initdb.d/

volumes:
  db:
